INSERT INTO teams
    (teamLocation, teamMascot, teamAbbreviation, league, division)
VALUES
    ( 'Pittsburgh', 'Pirates', 'PIT', 'NL', 'Central' ),
    ( 'Texas', 'Rangers', 'TEX', 'AL', 'West' ),
    ( 'Kansas City', 'Royals', 'KC', 'AL', 'Central' ),
    ( 'Colorado', 'Rockies', 'COL', 'NL', 'West' ),
    ( 'St. Louis', 'Cardinals', 'STL', 'NL', 'Central' ),
    ( 'Minnesota', 'Twins', 'MIN', 'AL', 'Central' ),
    ( 'Chicago', 'Cubs', 'CHC', 'NL', 'Central' ),
    ( 'Tampa Bay', 'Rays', 'TB', 'AL', 'East' ),
    ( 'Seattle', 'Mariners', 'SEA', 'AL', 'West' ),
    ( 'Boston', 'Red Sox', 'BOS', 'AL', 'East' ),
    ( 'Oakland', 'Athletics', 'OAK', 'AL', 'West' ),
    ( 'Milwaukee', 'Brewers', 'MIL', 'NL', 'Central' ),
    ( 'Miami', 'Marlins', 'MIA', 'NL', 'East' ),
    ( 'Cleveland', 'Indians', 'CLE', 'AL', 'Central' ),
    ( 'San Francisco', 'Giants', 'SF', 'NL', 'West' ),
    ( 'Toronto', 'Blue Jays', 'TOR', 'AL', 'East' ),
    ( 'Los Angeles', 'Angels', 'LAA', 'AL', 'West' ),
    ( 'Atlanta', 'Braves', 'ATL', 'NL', 'East' ),
    ( 'Washington', 'Nationals', 'WSH', 'NL', 'East' ),
    ( 'Houston', 'Astros', 'HOU', 'AL', 'West' ),
    ( 'New York', 'Mets', 'NYM', 'NL', 'East' ),
    ( 'Cincinnati', 'Reds', 'CIN', 'NL', 'Central' ),
    ( 'Detroit', 'Tigers', 'DET', 'AL', 'Central' ),
    ( 'Baltimore', 'Orioles', 'BAL', 'AL', 'East' ),
    ( 'New York', 'Yankees', 'NYY', 'AL', 'East' ),
    ( 'San Diego', 'Padres', 'SD', 'NL', 'West' );

INSERT INTO games
    (startTime, homeTeamId, awayTeamId, homeScore, awayScore)
VALUES
    ( '2019-06-06 12:35:00',(SELECT id FROM teams WHERE teamAbbreviation = 'PIT'), (SELECT id FROM teams WHERE teamAbbreviation = 'ATL'), 6, 1 ),
    ( '2019-06-06 13:15:00',(SELECT id FROM teams WHERE teamAbbreviation = 'KC'),  (SELECT id FROM teams WHERE teamAbbreviation = 'BOS'), 5, 7 ),
    ( '2019-06-06 14:20:00',(SELECT id FROM teams WHERE teamAbbreviation = 'CHC'), (SELECT id FROM teams WHERE teamAbbreviation = 'COL'), 1, 3 ),
    ( '2019-06-06 13:15:00',(SELECT id FROM teams WHERE teamAbbreviation = 'STL'), (SELECT id FROM teams WHERE teamAbbreviation = 'CIN'), 3, 1 ),
    ( '2019-06-06 19:00:00',(SELECT id FROM teams WHERE teamAbbreviation = 'CLE'), (SELECT id FROM teams WHERE teamAbbreviation = 'MIN'), 4, 5 ),
    ( '2019-06-06 13:10:00',(SELECT id FROM teams WHERE teamAbbreviation = 'DET'), (SELECT id FROM teams WHERE teamAbbreviation = 'TB'), 1, 6 ),
    ( '2019-06-06 15:40:00',(SELECT id FROM teams WHERE teamAbbreviation = 'SEA'), (SELECT id FROM teams WHERE teamAbbreviation = 'HOU'), 7, 8 ),
    ( '2019-06-06 22:07:00',(SELECT id FROM teams WHERE teamAbbreviation = 'LAA'), (SELECT id FROM teams WHERE teamAbbreviation = 'OAK'), 4, 7 ),
    ( '2019-06-06 14:10:00',(SELECT id FROM teams WHERE teamAbbreviation = 'MIL'), (SELECT id FROM teams WHERE teamAbbreviation = 'MIA'), 5, 1 ),
    ( '2019-06-06 12:10:00',(SELECT id FROM teams WHERE teamAbbreviation = 'NYM'), (SELECT id FROM teams WHERE teamAbbreviation = 'SF'), 7, 3 ),
    ( '2019-06-06 19:00:00',(SELECT id FROM teams WHERE teamAbbreviation = 'TOR'), (SELECT id FROM teams WHERE teamAbbreviation = 'NYY'), 2, 6 ),
    ( '2019-06-06 22:10:00',(SELECT id FROM teams WHERE teamAbbreviation = 'SD'), (SELECT id FROM teams WHERE teamAbbreviation = 'WSH'), 5, 4 );

INSERT INTO players 
    (firstName, lastName, position, throws, hits, teamId)
VALUES
( "Chris","Archer","SP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "PIT" )),
( "Josh","Bell","1B","R","B", (SELECT id FROM teams WHERE teamAbbreviation = "PIT" )),
( "Francisco","Liriano","SP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "PIT" )),
( "Starling","Marte","CF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "PIT" )),
( "Colin","Moran","3B","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "PIT" )),
( "Kevin","Newman","SS","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "PIT" )),
( "Gregory","Polanco","RF","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "PIT" )),
( "Bryan","Reynolds","LF","R","B", (SELECT id FROM teams WHERE teamAbbreviation = "PIT" )),
( "Jacob","Stallings","C","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "PIT" )),
( "Cole","Tucker","SS","R","B", (SELECT id FROM teams WHERE teamAbbreviation = "PIT" )),
( "Felipe","Vazquez","RP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "PIT" )),
( "Elvis","Andrus","SS","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TEX" )),
( "Asdrubal","Cabrera","3B","R","B", (SELECT id FROM teams WHERE teamAbbreviation = "TEX" )),
( "Jesse","Chavez","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TEX" )),
( "Delino","DeShields","LF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TEX" )),
( "Ronald","Guzman","1B","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "TEX" )),
( "Ariel","Jurado","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TEX" )),
( "Shawn","Kelley","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TEX" )),
( "Isiah","Kiner-Falefa","C","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TEX" )),
( "Chris","Martin","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TEX" )),
( "Nomar","Mazara","RF","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "TEX" )),
( "Rougned","Odor","2B","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "TEX" )),
( "Hunter","Pence","RF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TEX" )),
( "Danny","Santana","CF","R","B", (SELECT id FROM teams WHERE teamAbbreviation = "TEX" )),
( "Scott","Barlow","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "KC" )),
( "Cheslor","Cuthbert","3B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "KC" )),
( "Danny","Duffy","SP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "KC" )),
( "Brian","Flynn","RP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "KC" )),
( "Cam","Gallagher","C","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "KC" )),
( "Alex","Gordon","LF","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "KC" )),
( "Billy","Hamilton","CF","R","B", (SELECT id FROM teams WHERE teamAbbreviation = "KC" )),
( "Nicky","Lopez","2B","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "KC" )),
( "Kevin","McCarthy","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "KC" )),
( "Whit","Merrifield","2B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "KC" )),
( "Adalberto","Mondesi","2B","R","B", (SELECT id FROM teams WHERE teamAbbreviation = "KC" )),
( "Ryan","O'Hearn","1B","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "KC" )),
( "Jorge","Soler","RF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "KC" )),
( "Nolan","Arenado","3B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "COL" )),
( "David","Dahl","LF","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "COL" )),
( "Ian","Desmond","1B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "COL" )),
( "Jairo","Diaz","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "COL" )),
( "Chris","Iannetta","C","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "COL" )),
( "Peter","Lambert","SP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "COL" )),
( "Scott","Oberg","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "COL" )),
( "Mark","Reynolds","1B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "COL" )),
( "Brendan","Rodgers","SS","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "COL" )),
( "Trevor","Story","SS","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "COL" )),
( "Raimel","Tapia","CF","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "COL" )),
( "Harrison","Bader","CF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "STL" )),
( "Matt","Carpenter","1B","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "STL" )),
( "Paul","DeJong","SS","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "STL" )),
( "Dexter","Fowler","RF","R","B", (SELECT id FROM teams WHERE teamAbbreviation = "STL" )),
( "John","Gant","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "STL" )),
( "Paul","Goldschmidt","1B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "STL" )),
( "Jordan","Hicks","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "STL" )),
( "Dakota","Hudson","SP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "STL" )),
( "Andrew","Miller","RP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "STL" )),
( "Marcell","Ozuna","LF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "STL" )),
( "Matt","Wieters","C","R","B", (SELECT id FROM teams WHERE teamAbbreviation = "STL" )),
( "Kolten","Wong","2B","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "STL" )),
( "Ehire","Adrianza","SS","R","B", (SELECT id FROM teams WHERE teamAbbreviation = "MIN" )),
( "Willians","Astudillo","C","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIN" )),
( "Jose","Berrios","SP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIN" )),
( "C.J.","Cron","1B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIN" )),
( "Mitch","Garver","C","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIN" )),
( "Marwin","Gonzalez","3B","R","B", (SELECT id FROM teams WHERE teamAbbreviation = "MIN" )),
( "Max","Kepler","RF","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "MIN" )),
( "Matt","Magill","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIN" )),
( "Trevor","May","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIN" )),
( "Jorge","Polanco","SS","R","B", (SELECT id FROM teams WHERE teamAbbreviation = "MIN" )),
( "Taylor","Rogers","RP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "MIN" )),
( "Eddie","Rosario","LF","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "MIN" )),
( "Jonathan","Schoop","2B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIN" )),
( "Albert","Almora Jr.","CF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "CHC" )),
( "Javier","Baez","SS","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "CHC" )),
( "David","Bote","3B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "CHC" )),
( "Kris","Bryant","3B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "CHC" )),
( "Willson","Contreras","C","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "CHC" )),
( "Daniel","Descalso","3B","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "CHC" )),
( "Carl","Edwards Jr.","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "CHC" )),
( "Jose","Quintana","SP","L","R", (SELECT id FROM teams WHERE teamAbbreviation = "CHC" )),
( "Anthony","Rizzo","1B","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "CHC" )),
( "Kyle","Ryan","SP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "CHC" )),
( "Kyle","Schwarber","LF","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "CHC" )),
( "Willy","Adames","SS","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TB" )),
( "Christian","Arroyo","3B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TB" )),
( "Jalen","Beeks","RP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "TB" )),
( "Diego","Castillo","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TB" )),
( "Travis","d'Arnaud","C","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TB" )),
( "Yandy","Diaz","3B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TB" )),
( "Avisail","Garcia","RF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TB" )),
( "Kevin","Kiermaier","CF","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "TB" )),
( "Austin","Meadows","CF","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "TB" )),
( "Tommy","Pham","CF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TB" )),
( "Daniel","Robertson","2B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TB" )),
( "Chaz","Roe","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TB" )),
( "Ryne","Stanek","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TB" )),
( "Hunter","Wood","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TB" )),
( "Austin","Adams","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "SEA" )),
( "Anthony","Bass","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "SEA" )),
( "Gerson","Bautista","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "SEA" )),
( "Brandon","Brennan","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "SEA" )),
( "Roenis","Elias","SP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "SEA" )),
( "Edwin","Encarnacion","DH","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "SEA" )),
( "Matt","Festa","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "SEA" )),
( "Cory","Gearrin","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "SEA" )),
( "Mitch","Haniger","RF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "SEA" )),
( "Shed","Long","2B","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "SEA" )),
( "Tommy","Milone","SP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "SEA" )),
( "Dylan","Moore","3B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "SEA" )),
( "Omar","Narvaez","C","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "SEA" )),
( "Domingo","Santana","RF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "SEA" )),
( "Kyle","Seager","3B","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "SEA" )),
( "Mallex","Smith","CF","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "SEA" )),
( "Daniel","Vogelbach","1B","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "SEA" )),
( "Matt","Barnes","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "BOS" )),
( "Andrew","Benintendi","LF","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "BOS" )),
( "Mookie","Betts","RF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "BOS" )),
( "Xander","Bogaerts","SS","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "BOS" )),
( "Jackie","Bradley Jr.","CF","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "BOS" )),
( "Ryan","Brasier","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "BOS" )),
( "Colten","Brewer","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "BOS" )),
( "Michael","Chavis","3B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "BOS" )),
( "Rafael","Devers","3B","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "BOS" )),
( "Heath","Hembree","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "BOS" )),
( "J.D.","Martinez","LF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "BOS" )),
( "Eduardo","Nunez","2B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "BOS" )),
( "Josh","Taylor","RP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "BOS" )),
( "Christian","Vazquez","C","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "BOS" )),
( "Marcus","Walden","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "BOS" )),
( "Ryan","Weber","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "BOS" )),
( "Ryan","Buchter","RP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "OAK" )),
( "Mark","Canha","1B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "OAK" )),
( "Matt","Chapman","3B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "OAK" )),
( "Khris","Davis","LF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "OAK" )),
( "Mike","Fiers","SP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "OAK" )),
( "Liam","Hendriks","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "OAK" )),
( "Ramon","Laureano","CF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "OAK" )),
( "Josh","Phegley","C","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "OAK" )),
( "Chad","Pinder","SS","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "OAK" )),
( "Stephen","Piscotty","RF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "OAK" )),
( "Jurickson","Profar","SS","R","B", (SELECT id FROM teams WHERE teamAbbreviation = "OAK" )),
( "Marcus","Semien","SS","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "OAK" )),
( "Joakim","Soria","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "OAK" )),
( "Lou","Trivino","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "OAK" )),
( "Jesus","Aguilar","1B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIL" )),
( "Orlando","Arcia","SS","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIL" )),
( "Ryan","Braun","LF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIL" )),
( "Lorenzo","Cain","CF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIL" )),
( "Josh","Hader","RP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "MIL" )),
( "Jeremy","Jeffress","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIL" )),
( "Mike","Moustakas","2B","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "MIL" )),
( "Freddy","Peralta","SP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIL" )),
( "Hernan","Perez","3B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIL" )),
( "Manny","Pina","C","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIL" )),
( "Christian","Yelich","RF","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "MIL" )),
( "Jorge","Alfaro","C","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIA" )),
( "Brian","Anderson","3B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIA" )),
( "Austin","Brice","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIA" )),
( "Starlin","Castro","2B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIA" )),
( "Garrett","Cooper","LF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIA" )),
( "Austin","Dean","LF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIA" )),
( "Tayron","Guerrero","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIA" )),
( "Harold","Ramirez","RF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIA" )),
( "JT","Riddle","SS","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "MIA" )),
( "Miguel","Rojas","SS","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIA" )),
( "Sergio","Romo","SP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIA" )),
( "Caleb","Smith","SP","L","R", (SELECT id FROM teams WHERE teamAbbreviation = "MIA" )),
( "Trevor","Bauer","SP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "CLE" )),
( "Jake","Bauers","LF","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "CLE" )),
( "Jon","Edwards","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "CLE" )),
( "Jason","Kipnis","2B","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "CLE" )),
( "Francisco","Lindor","SS","R","B", (SELECT id FROM teams WHERE teamAbbreviation = "CLE" )),
( "Jordan","Luplow","RF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "CLE" )),
( "Leonys","Martin","CF","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "CLE" )),
( "Tyler","Naquin","CF","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "CLE" )),
( "Roberto","Perez","C","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "CLE" )),
( "Jose","Ramirez","2B","R","B", (SELECT id FROM teams WHERE teamAbbreviation = "CLE" )),
( "Carlos","Santana","1B","R","B", (SELECT id FROM teams WHERE teamAbbreviation = "CLE" )),
( "Josh","Smith","RP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "CLE" )),
( "Shaun","Anderson","SP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "SF" )),
( "Brandon","Belt","1B","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "SF" )),
( "Brandon","Crawford","SS","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "SF" )),
( "Steven","Duggar","CF","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "SF" )),
( "Mark","Melancon","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "SF" )),
( "Reyes","Moronta","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "SF" )),
( "Joe","Panik","2B","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "SF" )),
( "Kevin","Pillar","CF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "SF" )),
( "Pablo","Sandoval","3B","R","B", (SELECT id FROM teams WHERE teamAbbreviation = "SF" )),
( "Stephen","Vogt","C","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "SF" )),
( "Tony","Watson","RP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "SF" )),
( "Mike","Yastrzemski","LF","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "SF" )),
( "Brandon","Drury","3B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TOR" )),
( "Freddy","Galvis","SS","R","B", (SELECT id FROM teams WHERE teamAbbreviation = "TOR" )),
( "Randal","Grichuk","LF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TOR" )),
( "Vladimir","Guerrero Jr.","3B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TOR" )),
( "Lourdes","Gurriel Jr.","2B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TOR" )),
( "Teoscar","Hernandez","RF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TOR" )),
( "Edwin","Jackson","SP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TOR" )),
( "Elvis","Luciano","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TOR" )),
( "Luke","Maile","C","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "TOR" )),
( "Tim","Mayza","RP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "TOR" )),
( "Thomas","Pannone","RP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "TOR" )),
( "Justin","Smoak","1B","L","B", (SELECT id FROM teams WHERE teamAbbreviation = "TOR" )),
( "Eric","Sogard","2B","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "TOR" )),
( "Jaime","Barria","SP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "LAA" )),
( "Kole","Calhoun","RF","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "LAA" )),
( "David","Fletcher","SS","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "LAA" )),
( "Dustin","Garneau","C","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "LAA" )),
( "Brian","Goodwin","CF","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "LAA" )),
( "Tommy","La Stella","3B","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "LAA" )),
( "Shohei","Ohtani","DH","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "LAA" )),
( "Luis","Rengifo","2B","R","B", (SELECT id FROM teams WHERE teamAbbreviation = "LAA" )),
( "Tyler","Skaggs","SP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "LAA" )),
( "Mike","Trout","CF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "LAA" )),
( "Jared","Walsh","1B","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "LAA" )),
( "Ronald","Acuna Jr.","LF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "ATL" )),
( "Ozzie","Albies","2B","R","B", (SELECT id FROM teams WHERE teamAbbreviation = "ATL" )),
( "Josh","Donaldson","3B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "ATL" )),
( "Mike","Foltynewicz","SP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "ATL" )),
( "Freddie","Freeman","1B","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "ATL" )),
( "Nick","Markakis","RF","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "ATL" )),
( "Brian","McCann","C","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "ATL" )),
( "Sean","Newcomb","SP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "ATL" )),
( "Austin","Riley","3B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "ATL" )),
( "Dansby","Swanson","SS","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "ATL" )),
( "Jacob","Webb","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "ATL" )),
( "Patrick","Corbin","SP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "WSH" )),
( "Brian","Dozier","2B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "WSH" )),
( "Yan","Gomes","C","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "WSH" )),
( "Matt","Grace","RP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "WSH" )),
( "Javy","Guerra","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "WSH" )),
( "Howie","Kendrick","2B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "WSH" )),
( "Anthony","Rendon","3B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "WSH" )),
( "Victor","Robles","CF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "WSH" )),
( "Tony","Sipp","RP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "WSH" )),
( "Juan","Soto","LF","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "WSH" )),
( "Michael","Taylor","CF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "WSH" )),
( "Trea","Turner","SS","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "WSH" )),
( "Michael","Brantley","LF","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "HOU" )),
( "Alex","Bregman","3B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "HOU" )),
( "Robinson","Chirinos","C","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "HOU" )),
( "Chris","Devenski","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "HOU" )),
( "Derek","Fisher","CF","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "HOU" )),
( "Yuli","Gurriel","1B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "HOU" )),
( "Will","Harris","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "HOU" )),
( "Josh","James","SP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "HOU" )),
( "Tony","Kemp","LF","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "HOU" )),
( "Jake","Marisnick","CF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "HOU" )),
( "Jack","Mayfield","2B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "HOU" )),
( "Roberto","Osuna","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "HOU" )),
( "Ryan","Pressly","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "HOU" )),
( "Hector","Rondon","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "HOU" )),
( "Justin","Verlander","SP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "HOU" )),
( "Tyler","White","2B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "HOU" )),
( "Pete","Alonso","1B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "NYM" )),
( "Michael","Conforto","RF","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "NYM" )),
( "Jeurys","Familia","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "NYM" )),
( "Todd","Frazier","3B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "NYM" )),
( "Adeiny","Hechavarria","SS","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "NYM" )),
( "Juan","Lagares","CF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "NYM" )),
( "Seth","Lugo","SP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "NYM" )),
( "Tomas","Nido","C","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "NYM" )),
( "Amed","Rosario","SS","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "NYM" )),
( "Dominic","Smith","1B","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "NYM" )),
( "Zack","Wheeler","SP","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "NYM" )),
( "Tucker","Barnhart","C","R","B", (SELECT id FROM teams WHERE teamAbbreviation = "CIN" )),
( "Anthony","DeSclafani","SP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "CIN" )),
( "Derek","Dietrich","LF","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "CIN" )),
( "Amir","Garrett","RP","L","R", (SELECT id FROM teams WHERE teamAbbreviation = "CIN" )),
( "Jose","Iglesias","SS","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "CIN" )),
( "Michael","Lorenzen","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "CIN" )),
( "Wandy","Peralta","RP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "CIN" )),
( "Yasiel","Puig","RF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "CIN" )),
( "Nick","Senzel","3B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "CIN" )),
( "Eugenio","Suarez","3B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "CIN" )),
( "Joey","Votto","1B","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "CIN" )),
( "Jesse","Winker","RF","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "CIN" )),
( "Austin","Adams","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "DET" )),
( "Victor","Alcantara","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "DET" )),
( "Gordon","Beckham","3B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "DET" )),
( "Nicholas","Castellanos","RF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "DET" )),
( "Brandon","Dixon","LF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "DET" )),
( "Buck","Farmer","RP","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "DET" )),
( "Niko","Goodrum","SS","R","B", (SELECT id FROM teams WHERE teamAbbreviation = "DET" )),
( "Grayson","Greiner","C","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "DET" )),
( "JaCoby","Jones","LF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "DET" )),
( "Dawel","Lugo","2B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "DET" )),
( "Daniel","Norris","SP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "DET" )),
( "Ronny","Rodriguez","3B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "DET" )),
( "Christin","Stewart","LF","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "DET" )),
( "Daniel","Stumpf","RP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "DET" )),
( "Hanser","Alberto","SS","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "BAL" )),
( "Miguel","Castro","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "BAL" )),
( "Chris","Davis","1B","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "BAL" )),
( "David","Hess","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "BAL" )),
( "Trey","Mancini","LF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "BAL" )),
( "Richie","Martin","SS","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "BAL" )),
( "Renato","Nunez","3B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "BAL" )),
( "Rio","Ruiz","3B","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "BAL" )),
( "Chance","Sisco","C","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "BAL" )),
( "Dwight","Smith Jr.","RF","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "BAL" )),
( "Stevie","Wilkerson","SS","R","B", (SELECT id FROM teams WHERE teamAbbreviation = "BAL" )),
( "Aroldis","Chapman","RP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "NYY" )),
( "Thairo","Estrada","SS","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "NYY" )),
( "Clint","Frazier","LF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "NYY" )),
( "Chad","Green","RP","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "NYY" )),
( "J.A.","Happ","SP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "NYY" )),
( "Aaron","Hicks","CF","R","B", (SELECT id FROM teams WHERE teamAbbreviation = "NYY" )),
( "DJ","LeMahieu","2B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "NYY" )),
( "Cameron","Maybin","LF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "NYY" )),
( "Kendrys","Morales","DH","R","B", (SELECT id FROM teams WHERE teamAbbreviation = "NYY" )),
( "Gary","Sanchez","C","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "NYY" )),
( "Gio","Urshela","3B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "NYY" )),
( "Luke","Voit","1B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "NYY" )),
( "Austin","Hedges","C","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "SD" )),
( "Ian","Kinsler","2B","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "SD" )),
( "Joey","Lucchesi","SP","L","L", (SELECT id FROM teams WHERE teamAbbreviation = "SD" )),
( "Manny","Machado","SS","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "SD" )),
( "Manuel","Margot","CF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "SD" )),
( "Wil","Myers","RF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "SD" )),
( "Hunter","Renfroe","RF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "SD" )),
( "Franmil","Reyes","CF","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "SD" )),
( "Craig","Stammen","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "SD" )),
( "Fernando","Tatis Jr.","SS","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "SD" )),
( "Trey","Wingenter","RP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "SD" )),
( "Matt","Wisler","SP","R","R", (SELECT id FROM teams WHERE teamAbbreviation = "SD" )),
( "Kirby","Yates","RP","R","L", (SELECT id FROM teams WHERE teamAbbreviation = "SD" ));